uint64 timestamp			 # microseconds since system boot, needed to integrate

float32 probe_alpha
float32 probe_beta
float32 probe_airspeed
float32 probe_as1
float32 probe_as2
float32 probe_as3
float32 probe_as4
float32 probe_as5
float32 probe_as6
float32 probe_as7
float32 probe_dp1
float32 probe_dp2
float32 probe_dp3
float32 probe_dp4
float32 probe_dp5
float32 probe_dp6
float32 probe_dp7
float32 probe_total_pressure
float32 probe_static_pressure
float32 probe_checkerr_read
float32 probe_checkerr_cal
float32 probe_checkerr_cmp

