#!/bin/sh
#
# @name Quadrotor X Tailsitter
#
# @type VTOL Quad Tailsitter
# @class VTOL
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 4
# @output MAIN4 motor 5
# @output MAIN5 elevon left
# @output MAIN6 elevon right
# @output MAIN7 canard surface
# @output MAIN8 rudder
# @output AUX1 left trans servo
# @output AUX2 right trans servo
#
# @maintainer Roman Bapst <roman@px4.io>
# editer Qichang Chen     <bluecat1997@sina.cn>
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set PWM_MAX 2000
	param set PWM_RATE 400

	param set VT_MOT_COUNT 4
	param set VT_IDLE_PWM_MC  1080
	param set VT_TYPE 0
	param set VT_ELEV_MC_LOCK 1

	# Indicate that FW roll direction was fixed in mixer, to be removed in v1.10
	param set V19_VT_ROLLDIR 0


	param set PWM_AUX_MIN1 900
	param set PWM_AUX_MAX1 2100
	param set PWM_AUX_MIN2 900
	param set PWM_AUX_MAX2 2100
fi

set MAV_TYPE 20

set MIXER quad_x_vtol
set MIXER_AUX quad_x_vtol   #for NUAA Transwing

set PWM_OUT 1234
