#!/bin/sh
#
# @name NUAA V-Bet
#
# @type VTOL Duo Tailsitter
# @class VTOL
#
# @output MAIN1 servo front
# @output MAIN2 servo right
# @output MAIN3 servo back
# @output MAIN4 servo left
# @output MAIN5 motor up
# @output MAIN6 motor down
# @output MAIN7 motor left flap
# @output MAIN8 motor right flap
# @maintainer Qiochang Chen <bluecat1997@sina.cn>
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set MAV_TYPE 19

	param set VT_IDLE_PWM_MC  1080
	param set VT_ELEV_MC_LOCK 1
	param set VT_MOT_ID 56
	param set VT_TYPE 0
fi

set MAV_TYPE 19

set MIXER nuaa_vbat_8
set MIXER_AUX nuaa_vbat_8
set PWM_OUT 12345678
set PWM_AUX_OUT 1234
